name: runner_flutter
description: Endless runner 2.5D - Trabajo 2 Laboratorio de Apps Moviles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/character/kenney_platformerCharacters/adventurer_vector.svg
    - assets/images/character/player_atlas.png
