import 'dart:ui';

/// Sprites de 8 bits de los zombis, dibujados como cuadrículas de texto: cada
/// carácter es un píxel y '.' es transparente. Siguen la misma lógica que el
/// atlas del corredor (contorno oscuro, luz arriba a la izquierda, paleta
/// chica), pero sin assets: son constantes en código, así que no hay carga
/// asíncrona ni nada que pueda faltar.
///
/// Letras de la paleta (ver [ZombiePalette.build]):
///  O contorno · K/k/q piel (base/sombra/luz) · S/s/z ropa · P/p pantalón
///  H/h pelo · W/w camisa blanca · D zapato · B/b sangre (clara/oscura)
///  T hueso/dientes · R/r corbata · E ojos · N mancha.
class PixelSprite {
  PixelSprite(this.rows)
      : width = rows.first.length,
        height = rows.length;

  final List<String> rows;
  final int width;
  final int height;

  Map<String, Path>? _paths;

  /// Un [Path] por letra, armado la primera vez que se dibuja y reusado
  /// después: los píxeles contiguos de una fila se funden en un solo rectángulo.
  Map<String, Path> get paths => _paths ??= _build();

  Map<String, Path> _build() {
    final out = <String, Path>{};
    for (var y = 0; y < height; y++) {
      final row = rows[y];
      var x = 0;
      while (x < width) {
        final c = row[x];
        var end = x;
        while (end < width && row[end] == c) {
          end++;
        }
        if (c != '.') {
          (out[c] ??= Path()).addRect(
            Rect.fromLTWH(x.toDouble(), y.toDouble(), (end - x).toDouble(), 1),
          );
        }
        x = end;
      }
    }
    return out;
  }

  /// Dibuja el sprite estirado a [dst] con [palette]. Sin antialias para que
  /// los píxeles queden nítidos a cualquier escala; [alpha] aplica la fundida.
  void draw(
    Canvas canvas,
    Rect dst,
    Map<String, Color> palette, {
    double alpha = 1,
  }) {
    canvas.save();
    canvas.translate(dst.left, dst.top);
    canvas.scale(dst.width / width, dst.height / height);
    final paint = Paint()..isAntiAlias = false;
    paths.forEach((letter, path) {
      final color = palette[letter];
      if (color == null) return;
      paint.color = alpha >= 1 ? color : color.withValues(alpha: alpha);
      canvas.drawPath(path, paint);
    });
    canvas.restore();
  }
}

/// Paletas de los zombis.
abstract final class ZombiePalette {
  static const Color _ink = Color(0xFF140E0C);

  static Color _mix(Color a, Color b, double t) => Color.lerp(a, b, t)!;

  /// Paleta completa a partir de los colores base. [shade] (0..1) oscurece
  /// todo menos los ojos: las filas lejanas de la horda se hunden en la niebla.
  static Map<String, Color> build({
    required Color skin,
    required Color clothes,
    required Color eyes,
    Color hair = const Color(0xFF2A2018),
    Color pants = const Color(0xFF2E3544),
    double shade = 0,
  }) {
    Color t(Color c) => shade <= 0 ? c : _mix(c, const Color(0xFF000000), shade);
    const black = Color(0xFF000000);
    const white = Color(0xFFFFFFFF);
    return {
      'O': _ink,
      'K': t(skin),
      'k': t(_mix(skin, const Color(0xFF0A0F08), 0.38)),
      'q': t(_mix(skin, white, 0.22)),
      'S': t(clothes),
      's': t(_mix(clothes, black, 0.40)),
      'z': t(_mix(clothes, white, 0.16)),
      'P': t(pants),
      'p': t(_mix(pants, black, 0.35)),
      'H': t(hair),
      'h': t(_mix(hair, black, 0.35)),
      'W': t(const Color(0xFFD8D3C4)),
      'w': t(const Color(0xFF9E998C)),
      'D': t(const Color(0xFF1B1511)),
      'B': t(const Color(0xFF8E1B1B)),
      'b': t(const Color(0xFF3A0808)),
      'T': t(const Color(0xFFE8E0C8)),
      'R': t(const Color(0xFF8A2020)),
      'r': t(const Color(0xFF5A1414)),
      'E': eyes,
      'N': t(_mix(skin, const Color(0xFF3C5230), 0.5)),
    };
  }
}

/// Cuadros de animación de cada zombi. Cada lista tiene dos cuadros que se
/// alternan al caminar (una pierna y una mano se levantan mientras la otra
/// apoya).
abstract final class ZombieSprites {
  static final PixelSprite slow0 = PixelSprite(_slow[0]);
  static final PixelSprite slow1 = PixelSprite(_slow[1]);
  static final PixelSprite normal0 = PixelSprite(_normal[0]);
  static final PixelSprite normal1 = PixelSprite(_normal[1]);
  static final PixelSprite fast0 = PixelSprite(_fast[0]);
  static final PixelSprite fast1 = PixelSprite(_fast[1]);

  static const List<List<String>> _slow = [
    [
      '...........OO...........',
      '.......O.OOqkOO.........',
      '.......OOOqKKqkO........',
      '.......OqOOKKKKkO.......',
      '......OOOOKKKKOOOO......',
      '......OqKKKKKKKKkO......',
      '.....OOWOKKKKOWOKkO.....',
      '.O...OOEEKKKKOEEKkO.....',
      'OqO..OOOOKKKKOOOKkO.....',
      'qOqO..OqKKKkkKKKkO....O.',
      'qqkO..OkTOTOTOTOkO...OqO',
      'kKkO...OOOOOOOOOO...OqOq',
      'OqKkO..OOTOROTOOO...Oqqk',
      'OqKkO..OkBkkkkBkO...OkKk',
      'OqKkOOOOOBOOOOOOOOOO.Oqk',
      'OqKKzzzzqqqqqqqqzzzsOOqk',
      'OqKKKKSSKKKKKKKKSSSSqqKk',
      'OqKKKKSSKKKKKKKKSSSSKKKk',
      'OqKKKKSSKKKKKKKKSSSSKKKk',
      'OqKKKKKKKKKKKKbBKKSKkKKk',
      'OqBKKKKKKKKKKKbKKKskOqBk',
      'OqKKKKKKKKKKKKKbBKKkOqKk',
      'OqKKKKkkkkkkKKKbKKKkOkKk',
      'OkkkKKKKKKKkKKKKbBKkOOkk',
      '.OOOqKKKKKkOqKKbKKKkO.OO',
      '...OqKKkkkkkkKKbBKKkO...',
      '...OqKKKKKKKKKKKKKKkO...',
      '...OqKKKKKKKKKKKKKKkO...',
      '...OkKkkkkkkKKKKKKKkO...',
      '....OqKKKKKKKKKKKKkO....',
      '....OqKKKKKKKKKKKKkO....',
      '...OPPKKKKKKKKKKKKPpO...',
      '...OPPPKKKKKKKKKKPPpO...',
      '...OPPPPPKKkkKKBBPPpO...',
      '...OPpPpPppOOPBBBPPpO...',
      '...OpOpOpOpOOPPPPPPpO...',
      '....OqKqKkO.OPPPPPPpO...',
      '....OqKKKkO.OPpPpPppO...',
      '....OqKKKkO.OpOpOpOpO...',
      '...OqKkKkKkO.OqKqKkO....',
      '...OkkkkkkkO.OqKKKkO....',
      '....OOOOOOO..OqKKKkO....',
      '............OqKkKkKkO...',
      '............OkkkkkkkO...',
    ],
    [
      '...........OO...........',
      '.......O.OOqkOO.........',
      '.......OOOqKKqkO........',
      '.......OqOOKKKKkO.......',
      '......OOOOKKKKOOOO......',
      '......OqKKKKKKKKkO......',
      '.....OOWOKKKKOWOKkO.....',
      '.....OOEEKKKKOEEKkO...O.',
      '.....OOOOKKKKOOOKkO..OqO',
      '.O....OqKKKkkKKKkO..OqOq',
      'OqO...OkTOTOTOTOkO..Oqqk',
      'qOqO...OOOOOOOOOO...OkKk',
      'qqkO...OOTOROTOOO....Oqk',
      'kKkO...OkBkkkkBkO....Oqk',
      'OqKkOOOOOBOOOOOOOOOO.Oqk',
      'OqKKzzzzqqqqqqqqzzzsOOqk',
      'OqKKKKSSKKKKKKKKSSSSqqKk',
      'OqKKKKSSKKKKKKKKSSSSKKKk',
      'OqKKKKSSKKKKKKKKSSSSKKKk',
      'OqKKKKKKKKKKKKbBKKSKkKKk',
      'OqBKKKKKKKKKKKbKKKskOqBk',
      'OqKKKKKKKKKKKKKbBKKkOqKk',
      'OqKKKKkkkkkkKKKbKKKkOkKk',
      'OkkkKKKKKKKkKKKKbBKkOOkk',
      '.OOOqKKKKKkOqKKbKKKkO.OO',
      '...OqKKkkkkkkKKbBKKkO...',
      '...OqKKKKKKKKKKKKKKkO...',
      '...OqKKKKKKKKKKKKKKkO...',
      '...OkKkkkkkkKKKKKKKkO...',
      '....OqKKKKKKKKKKKKkO....',
      '....OqKKKKKKKKKKKKkO....',
      '...OPPKKKKKKKKKKKKPpO...',
      '...OPPPKKKKKKKKKKPPpO...',
      '...OPPPPPKKkkKKBBPPpO...',
      '...OPPPPPPpOOPBBBPppO...',
      '...OPPPPPPpOOpOpOpOpO...',
      '...OPPPPPPpO.OqKqKkO....',
      '...OPpPpPppO.OqKKKkO....',
      '...OpOpOpOpO.OqKKKkO....',
      '....OqKqKkO.OqKkKkKkO...',
      '....OqKKKkO.OkkkkkkkO...',
      '....OqKKKkO..OOOOOOO....',
      '...OqKkKkKkO............',
      '...OkkkkkkkO............',
    ],
  ];

  static const List<List<String>> _normal = [
    [
      '...OhOhOhOhOhO....',
      '...OhOhOhOhOhO....',
      '...OHHHHHHHHHhO...',
      '...OHHHHHHHHHhO...',
      '...OHKKKKKKNNO....',
      '...OHKKKKKKNNkO...',
      '.O.OHOOEKKOOOkO...',
      'OqOOqOEOKKOEOkO...',
      'qOqOqKKKKKKKKkO.O.',
      'qqkOqKKKkkKBBkOOqO',
      'kKkOkKKKKKKKKkOqOq',
      'OqkOOkTOTOTOkOOqqk',
      'OqkO.OOBOOTOO.OkKk',
      'OqkOOWWBKKWWwO.Oqk',
      'OqkOzWWWSSWWWsOOqk',
      'OkKqSSSWRRWSsszzKk',
      '.OqKSSSSRRSSssSKKk',
      '.OqKSSSSRRSSssSKkO',
      '.OBKSBbbRRSSsssKBO',
      '.OqKSTTTRRSSssOqkO',
      '.OssSbbbRRSSssOssO',
      '..OOzTTTRRSSssOOO.',
      '...OzbbbRRSBBsO...',
      '...OzTTTRRSBBsO...',
      '...OzbbBRRSBBsO...',
      '...OzSSSRRSBBsO...',
      '...OzSSSRrSsssO...',
      '...OzSSSSSSsssO...',
      '...OzSSSSsSsssO...',
      '...OPSPPsOPSPpO...',
      '...OPPPpOOPPPpO...',
      '...OPpPpOOPPPpO...',
      '...OpOpO.OPPPpO...',
      '....OkkO.OPpPpO...',
      '....OkkO.OpOpO....',
      '....OkkO..OkkO....',
      '...ODDDDO.OkkO....',
      '...ODDDDO.OkkO....',
      '....OOOO.ODDDDO...',
      '.........ODDDDO...',
    ],
    [
      '...OhOhOhOhOhO....',
      '...OhOhOhOhOhO....',
      '...OHHHHHHHHHhO...',
      '...OHHHHHHHHHhO...',
      '...OHKKKKKKNNO....',
      '...OHKKKKKKNNkO...',
      '...OHOOEKKOOOkO.O.',
      '...OqOEOKKOEOkOOqO',
      '.O.OqKKKKKKKKkOqOq',
      'OqOOqKKKkkKBBkOqqk',
      'qOqOkKKKKKKKKkOkKk',
      'qqkOOkTOTOTOkO.Oqk',
      'kKkO.OOBOOTOO..Oqk',
      'OqkOOWWBKKWWwO.Oqk',
      'OqkOzWWWSSWWWsOOqk',
      'OqKzSSSWRRWSsszqKk',
      'OkKKSSSSRRSSssSKkO',
      '.OqKSSSSRRSSssSKkO',
      '.OBKSBbbRRSSsssKBO',
      '.OqKSTTTRRSSssOqkO',
      '.OssSbbbRRSSssOssO',
      '..OOzTTTRRSSssOOO.',
      '...OzbbbRRSBBsO...',
      '...OzTTTSRRBBsO...',
      '...OzbbBSRRBBsO...',
      '...OzSSSSRRBBsO...',
      '...OzSSSSRrsssO...',
      '...OzSSSSSSsssO...',
      '...OzSSSSsSsssO...',
      '...OPSPPsOPSPpO...',
      '...OPPPpOOPPPpO...',
      '...OPBPpOOPpPpO...',
      '...OPPPpOOpOpO....',
      '...OPpPpO.OkkO....',
      '...OpOpO..OkkO....',
      '....OkkO..OkkO....',
      '....OkkO.ODDDDO...',
      '....OkkO.ODDDDO...',
      '...ODDDDO.OOOO....',
      '...ODDDDO.........',
    ],
  ];

  static const List<List<String>> _fast = [
    [
      '.....OOOOOO.....',
      '....OzzzzzsO....',
      '...OzSSSSSSsO...',
      '..OzSSSSSSSSsO..',
      '.OzSssssssssSsO.',
      'OqSSOOKKKKOOSsO.',
      'qOzSOOOKKOOOSsO.',
      'qqSSOEEKKEEOSSqO',
      'kKSSKKKKKKKKSsOq',
      'OqSSKKKkkKKKSSqk',
      'OzSSKTOTOTOKSsKk',
      'OzSSKOOOOOOKsOzs',
      'OzSSSOORROOSsOzs',
      'OzSSSOTOTOOSsOzs',
      'OzSSSSSzzSBsSzSs',
      'OzSSSSSzzSBssSSs',
      'OzSSSSSzzSssOzSs',
      'OzSsSbbzzSssOsSs',
      'OssOzTTWWSssOOss',
      '.OOOzbbSSSssO.OO',
      '...OzTTSSSssO...',
      '...OzSSSSSssO...',
      '...OzsssssssO...',
      '...OzSSSSSssO...',
      '..OPSSSSSSsspO..',
      '..OPSSSssSsspO..',
      '..OPPPpOOPPPpO..',
      '..OPPPpOOPPPpO..',
      '..OPpPpOOPPPpO..',
      '..OpOpO.OPPPpO..',
      '...OqkO.OPpPpO..',
      '...OqkO.OpOpO...',
      '..OWDDDO.OqkO...',
      '..ODDDDO.OqkO...',
      '...OOOO.ODDDDO..',
      '........ODDDDO..',
    ],
    [
      '.....OOOOOO.....',
      '....OzzzzzsO....',
      '...OzSSSSSSsO...',
      '..OzSSSSSSSSsO..',
      '.OzSssssssssSsO.',
      '.OzSOOKKKKOOSSqO',
      '.OzSOOOKKOOOSsOq',
      'OqSSOEEKKEEOSSqk',
      'qOzSKKKKKKKKSSKk',
      'qqSSKKKkkKKKSSSs',
      'kKSSKTOTOTOKSsSs',
      'OqSSKOOOOOOKsOzs',
      'OzSSSOORROOSsOzs',
      'OzSSSOTOTOOSsOzs',
      'OzSSSSSzzSBsSzSs',
      'OzSSSSSzzSBssSSs',
      'OzSSSSSzzSssOzSs',
      'OzSsSbbzzSssOsSs',
      'OssOzTTWWSssOOss',
      '.OOOzbbSSSssO.OO',
      '...OzTTSSSssO...',
      '...OzSSSSSssO...',
      '...OzsssssssO...',
      '...OzSSSSSssO...',
      '..OPSSSSSSsspO..',
      '..OPSSSssSsspO..',
      '..OPPPpOOPPPpO..',
      '..OPPPpOOPPPpO..',
      '..OPPPpOOPpPpO..',
      '..OPPPpOOpOpO...',
      '..OPpPpO.OqkO...',
      '..OpOpO..OqkO...',
      '...OqkO.ODDDDO..',
      '...OqkO.ODDDDO..',
      '..OWDDDO.OOOO...',
      '..ODDDDO........',
    ],
  ];

  /// Zombis de espaldas de la horda: `back[estilo][variante][cuadro]`.
  /// Estilos: 0 camiseta, 1 campera (una mano colgando), 2 capucha, 3 torso al
  /// aire con columna y costillas. Las variantes cambian el peinado (pelo
  /// largo, corto o calvo) y la posición del desgarro de la espalda.
  static final List<List<List<PixelSprite>>> back = [
    [
      [
        PixelSprite(_back0),
        PixelSprite(_back1),
      ],
      [
        PixelSprite(_back2),
        PixelSprite(_back3),
      ],
      [
        PixelSprite(_back4),
        PixelSprite(_back5),
      ],
    ],
    [
      [
        PixelSprite(_back6),
        PixelSprite(_back7),
      ],
      [
        PixelSprite(_back8),
        PixelSprite(_back9),
      ],
      [
        PixelSprite(_back10),
        PixelSprite(_back11),
      ],
    ],
    [
      [
        PixelSprite(_back12),
        PixelSprite(_back13),
      ],
    ],
    [
      [
        PixelSprite(_back14),
        PixelSprite(_back15),
      ],
      [
        PixelSprite(_back16),
        PixelSprite(_back17),
      ],
      [
        PixelSprite(_back18),
        PixelSprite(_back19),
      ],
    ],
  ];

  static const List<String> _back0 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO..O.',
    'qqkOhHkHHHHhHHHHOOqO',
    'kKkOHHHHhHHHHHHhOqOq',
    'OqkOkhHHHHHHhHHkOqqk',
    'OqkOHHHHHhHHHHHHOkKk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOHHHHHhHHHHO.Oqk',
    'OqkOOHHhHHHHHHhO.Oqk',
    'OqkOzzzHKKKKHzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSbkkBSSSSsOqKk',
    'OqKkSSSbkkbSSSSsOkKk',
    'OkkOzSSbTkbSsSSsOOkk',
    '.OOOsSSbkTbSSSSsO.OO',
    '....OzSBkkbSSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back1 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO...O.',
    '....OHHHHHhHkHHO.OqO',
    '.O..OHHhHHHHHHhOOqOq',
    'OqOOhHkHHHHhHHHHOqqk',
    'qOqOHHHHhHHHHHHhOkKk',
    'qqkOkhHHHHHHhHHkOOqk',
    'kKkOHHHHHhHHHHHHOOqk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOHHHHHhHHHHO.Oqk',
    'OqkOOHHhHHHHHHhO.Oqk',
    'OqkOzzzHKKKKHzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSbkkBSSSSsOqKk',
    'OqKkSSSbkkbSSSSsOkKk',
    'OkkOzSSbTkbSsSSsOOkk',
    '.OOOsSSbkTbSSSSsO.OO',
    '....OzSBkkbSSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back2 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO..O.',
    'qqkOhHkHHHHhHHHHOOqO',
    'kKkOHHHHhHHHHHHhOqOq',
    'OqkOkhHHHHHHhHHkOqqk',
    'OqkOHHHHHhHHHHHHOkKk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOOkHHHhHHkOO.Oqk',
    'OqkOOOOqKHHKkOOO.Oqk',
    'OqkOzzzSKKKKSzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSSbkkBSSSsOqKk',
    'OqKkSSSSbkkbSSSsOkKk',
    'OkkOzSSsbTkbsSSsOOkk',
    '.OOOsSSSbkTbSSSsO.OO',
    '....OzSSBkkbSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back3 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO...O.',
    '....OHHHHHhHkHHO.OqO',
    '.O..OHHhHHHHHHhOOqOq',
    'OqOOhHkHHHHhHHHHOqqk',
    'qOqOHHHHhHHHHHHhOkKk',
    'qqkOkhHHHHHHhHHkOOqk',
    'kKkOHHHHHhHHHHHHOOqk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOOkHHHhHHkOO.Oqk',
    'OqkOOOOqKHHKkOOO.Oqk',
    'OqkOzzzSKKKKSzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSSbkkBSSSsOqKk',
    'OqKkSSSSbkkbSSSsOkKk',
    'OkkOzSSsbTkbsSSsOOkk',
    '.OOOsSSSbkTbSSSsO.OO',
    '....OzSSBkkbSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back4 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.O...OqKBKKKKkO.....',
    'OqO..OqKKBKBKkO.....',
    'qOqOOqKKKKBKKKkO..O.',
    'qqkOOqKKKKKKKKkO.OqO',
    'kKkOOqKKKKKKKKkOOqOq',
    'OqkOkqKKKKKKKKkkOqqk',
    'OqkOOkKKKKKKKKkOOkKk',
    'OqkO.OqKKKKKKkO..Oqk',
    'OqkO.OkKKKKKKkO..Oqk',
    'OqkOOOOqKKKKkOOO.Oqk',
    'OqkOzzzSKKKKSzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSbkkBSSSSsOqKk',
    'OqKkSSSbkkbSSSSsOkKk',
    'OkkOzSSbTkbSsSSsOOkk',
    '.OOOsSSbkTbSSSSsO.OO',
    '....OzSBkkbSSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back5 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.....OqKBKKKKkO...O.',
    '.....OqKKBKBKkO..OqO',
    '.O..OqKKKKBKKKkOOqOq',
    'OqO.OqKKKKKKKKkOOqqk',
    'qOqOOqKKKKKKKKkOOkKk',
    'qqkOkqKKKKKKKKkk.Oqk',
    'kKkOOkKKKKKKKKkO.Oqk',
    'OqkO.OqKKKKKKkO..Oqk',
    'OqkO.OkKKKKKKkO..Oqk',
    'OqkOOOOqKKKKkOOO.Oqk',
    'OqkOzzzSKKKKSzzsOOqk',
    'OqKqKSSSSSSSSSSSqqKk',
    'OqKKKSSsSSSSsSSSkKKk',
    'OqKKSSSbkkBSSSSsOqKk',
    'OqKkSSSbkkbSSSSsOkKk',
    'OkkOzSSbTkbSsSSsOOkk',
    '.OOOsSSbkTbSSSSsO.OO',
    '....OzSBkkbSSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back6 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO....',
    'qqkOhHkHHHHhHHHHO...',
    'kKkOHHHHhHHHHHHhO...',
    'OqkOkhHHHHHHhHHkO...',
    'OqkOHHHHHhHHHHHHO...',
    'OqkOHHhHHHHHHhHHO...',
    'OqkOOHHHHHhHHHHO....',
    'OqkOOHHhHHHHHHhO....',
    'OqkOzzzHKKKKHzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSbkkBSSSSSsSsO',
    'OqKsSSSbkkbSSSSsOsSs',
    'OssOzSSbTkbSsSSsOOqk',
    '.OOOsSSbkTbSSSSsOOqk',
    '....OzSBkkbSSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsO.Oqk',
    '....OPSPpSOPSPpOOqKk',
    '....OPpPpOOPPPpOOkkk',
    '....OpOpO.OPPPpO.OOO',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back7 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO.....',
    '....OHHHHHhHkHHO....',
    '.O..OHHhHHHHHHhO....',
    'OqOOhHkHHHHhHHHHO...',
    'qOqOHHHHhHHHHHHhO...',
    'qqkOkhHHHHHHhHHkO...',
    'kKkOHHHHHhHHHHHHO...',
    'OqkOHHhHHHHHHhHHO...',
    'OqkOOHHHHHhHHHHO....',
    'OqkOOHHhHHHHHHhO....',
    'OqkOzzzHKKKKHzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSbkkBSSSSSsSsO',
    'OqKsSSSbkkbSSSSsOsSs',
    'OssOzSSbTkbSsSSsOOqk',
    '.OOOsSSbkTbSSSSsOOqk',
    '....OzSBkkbSSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsOOqKk',
    '....OPSPpSOPSPpOOkkk',
    '....OPPPpOOPpPpO.OOO',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back8 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO....',
    'qqkOhHkHHHHhHHHHO...',
    'kKkOHHHHhHHHHHHhO...',
    'OqkOkhHHHHHHhHHkO...',
    'OqkOHHHHHhHHHHHHO...',
    'OqkOHHhHHHHHHhHHO...',
    'OqkOOOkHHHhHHkOO....',
    'OqkOOOOqKHHKkOOO....',
    'OqkOzzzSKKKKSzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSSbkkBSSSSsSsO',
    'OqKsSSSSbkkbSSSsOsSs',
    'OssOzSSsbTkbsSSsOOqk',
    '.OOOsSSSbkTbSSSsOOqk',
    '....OzSSBkkbSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsO.Oqk',
    '....OPSPpSOPSPpOOqKk',
    '....OPpPpOOPPPpOOkkk',
    '....OpOpO.OPPPpO.OOO',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back9 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO.....',
    '....OHHHHHhHkHHO....',
    '.O..OHHhHHHHHHhO....',
    'OqOOhHkHHHHhHHHHO...',
    'qOqOHHHHhHHHHHHhO...',
    'qqkOkhHHHHHHhHHkO...',
    'kKkOHHHHHhHHHHHHO...',
    'OqkOHHhHHHHHHhHHO...',
    'OqkOOOkHHHhHHkOO....',
    'OqkOOOOqKHHKkOOO....',
    'OqkOzzzSKKKKSzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSSbkkBSSSSsSsO',
    'OqKsSSSSbkkbSSSsOsSs',
    'OssOzSSsbTkbsSSsOOqk',
    '.OOOsSSSbkTbSSSsOOqk',
    '....OzSSBkkbSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsOOqKk',
    '....OPSPpSOPSPpOOkkk',
    '....OPPPpOOPpPpO.OOO',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back10 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.O...OqKBKKKKkO.....',
    'OqO..OqKKBKBKkO.....',
    'qOqOOqKKKKBKKKkO....',
    'qqkOOqKKKKKKKKkO....',
    'kKkOOqKKKKKKKKkO....',
    'OqkOkqKKKKKKKKkk....',
    'OqkOOkKKKKKKKKkO....',
    'OqkO.OqKKKKKKkO.....',
    'OqkO.OkKKKKKKkO.....',
    'OqkOOOOqKKKKkOOO....',
    'OqkOzzzSKKKKSzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSbkkBSSSSSsSsO',
    'OqKsSSSbkkbSSSSsOsSs',
    'OssOzSSbTkbSsSSsOOqk',
    '.OOOsSSbkTbSSSSsOOqk',
    '....OzSBkkbSSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsO.Oqk',
    '....OPSPpSOPSPpOOqKk',
    '....OPpPpOOPPPpOOkkk',
    '....OpOpO.OPPPpO.OOO',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back11 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.....OqKBKKKKkO.....',
    '.....OqKKBKBKkO.....',
    '.O..OqKKKKBKKKkO....',
    'OqO.OqKKKKKKKKkO....',
    'qOqOOqKKKKKKKKkO....',
    'qqkOkqKKKKKKKKkk....',
    'kKkOOkKKKKKKKKkO....',
    'OqkO.OqKKKKKKkO.....',
    'OqkO.OkKKKKKKkO.....',
    'OqkOOOOqKKKKkOOO....',
    'OqkOzzzSKKKKSzzsOO..',
    'OqKzSSSSSSSSSSSSzsO.',
    'OqKSSSSsSSSSsSSSSsO.',
    'OqKSSSSbkkBSSSSSsSsO',
    'OqKsSSSbkkbSSSSsOsSs',
    'OssOzSSbTkbSsSSsOOqk',
    '.OOOsSSbkTbSSSSsOOqk',
    '....OzSBkkbSSSsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSSSSSBBBsO.Oqk',
    '....OzSsSSSSsSsO.Oqk',
    '....OzSSSSSSSSsO.Oqk',
    '....OzSSSssSSSsOOqKk',
    '....OPSPpSOPSPpOOkkk',
    '....OPPPpOOPpPpO.OOO',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back12 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOzzOO.......',
    '......OzzzzzsO......',
    '.O...OzSSzzSSsO.....',
    'OqO.OzSSSzzSSSsO....',
    'qOqOOzSSSzzSSSsO..O.',
    'qqkOzSSSSzzSSSSsOOqO',
    'kKkOzSSSSzzSSSSsOqOq',
    'OqkOsSSSSzzSSSSsOqqk',
    'OqkOOzSSSzzSSSsOOkKk',
    'OqkOOsSSSzzSSSsO.Oqk',
    'OqkO.OsSSzzSSsO..Oqk',
    'OqkOOOOzSSSSsOOO.Oqk',
    'OqkOzzzSSSSSSzzsOOqk',
    'OqKzSSSSSSSSSSSSzzKk',
    'OqKSSSSsSSSSsSSSsSKk',
    'OqKSSSSSbkkBSSSsOzKk',
    'OqKsSSSSbkkbSSSsOsKk',
    'OssOzSSsbTkbsSSsOOss',
    '.OOOsSSSbkTbSSSsO.OO',
    '....OzSSBkkbSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back13 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOzzOO.......',
    '......OzzzzzsO......',
    '.....OzSSzzSSsO...O.',
    '....OzSSSzzSSSsO.OqO',
    '.O..OzSSSzzSSSsOOqOq',
    'OqOOzSSSSzzSSSSsOqqk',
    'qOqOzSSSSzzSSSSsOkKk',
    'qqkOsSSSSzzSSSSsOOqk',
    'kKkOOzSSSzzSSSsO.Oqk',
    'OqkOOsSSSzzSSSsO.Oqk',
    'OqkO.OsSSzzSSsO..Oqk',
    'OqkOOOOzSSSSsOOO.Oqk',
    'OqkOzzzSSSSSSzzsOOqk',
    'OqKzSSSSSSSSSSSSzzKk',
    'OqKSSSSsSSSSsSSSsSKk',
    'OqKSSSSSbkkBSSSsOzKk',
    'OqKsSSSSbkkbSSSsOsKk',
    'OssOzSSsbTkbsSSsOOss',
    '.OOOsSSSbkTbSSSsO.OO',
    '....OzSSBkkbSSsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSBBBsO....',
    '....OzSSSSSBBBsO....',
    '....OzSsSSSSsSsO....',
    '....OzSSSSSSSSsO....',
    '....OzSSSssSSSsO....',
    '....OPSPpSOPSPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back14 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO..O.',
    'qqkOhHkHHHHhHHHHOOqO',
    'kKkOHHHHhHHHHHHhOqOq',
    'OqkOkhHHHHHHhHHkOqqk',
    'OqkOHHHHHhHHHHHHOkKk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOHHHHHhHHHHO.Oqk',
    'OqkOOHHhHHHHHHhO.Oqk',
    'OqkOqqqHKKKKHqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back15 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO...O.',
    '....OHHHHHhHkHHO.OqO',
    '.O..OHHhHHHHHHhOOqOq',
    'OqOOhHkHHHHhHHHHOqqk',
    'qOqOHHHHhHHHHHHhOkKk',
    'qqkOkhHHHHHHhHHkOOqk',
    'kKkOHHHHHhHHHHHHOOqk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOHHHHHhHHHHO.Oqk',
    'OqkOOHHhHHHHHHhO.Oqk',
    'OqkOqqqHKKKKHqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back16 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.O...OhHHHHkHhO.....',
    'OqO.OHHHHHhHkHHO....',
    'qOqOOHHhHHHHHHhO..O.',
    'qqkOhHkHHHHhHHHHOOqO',
    'kKkOHHHHhHHHHHHhOqOq',
    'OqkOkhHHHHHHhHHkOqqk',
    'OqkOHHHHHhHHHHHHOkKk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOOkHHHhHHkOO.Oqk',
    'OqkOOOOqKHHKkOOO.Oqk',
    'OqkOqqqKKKKKKqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back17 = [
    '....................',
    '....................',
    '.........OO.........',
    '.......OOHHOO.......',
    '......OHHhHHHO......',
    '.....OhHHHHkHhO...O.',
    '....OHHHHHhHkHHO.OqO',
    '.O..OHHhHHHHHHhOOqOq',
    'OqOOhHkHHHHhHHHHOqqk',
    'qOqOHHHHhHHHHHHhOkKk',
    'qqkOkhHHHHHHhHHkOOqk',
    'kKkOHHHHHhHHHHHHOOqk',
    'OqkOHHhHHHHHHhHHOOqk',
    'OqkOOOkHHHhHHkOO.Oqk',
    'OqkOOOOqKHHKkOOO.Oqk',
    'OqkOqqqKKKKKKqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

  static const List<String> _back18 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.O...OqKBKKKKkO.....',
    'OqO..OqKKBKBKkO.....',
    'qOqOOqKKKKBKKKkO..O.',
    'qqkOOqKKKKKKKKkO.OqO',
    'kKkOOqKKKKKKKKkOOqOq',
    'OqkOkqKKKKKKKKkkOqqk',
    'OqkOOkKKKKKKKKkOOkKk',
    'OqkO.OqKKKKKKkO..Oqk',
    'OqkO.OkKKKKKKkO..Oqk',
    'OqkOOOOqKKKKkOOO.Oqk',
    'OqkOqqqKKKKKKqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPpPpOOPPPpO....',
    '....OpOpO.OPPPpO....',
    '.....OkkO.OPpPpO....',
    '.....OkkO.OpOpO.....',
    '....ODDDDO.OkkO.....',
    '....ODDDDO.OkkO.....',
    '.....OOOO.ODDDDO....',
    '..........ODDDDO....',
  ];

  static const List<String> _back19 = [
    '....................',
    '....................',
    '....................',
    '.......OOOOOO.......',
    '......OqqqqqkO......',
    '.....OqKBKKKKkO...O.',
    '.....OqKKBKBKkO..OqO',
    '.O..OqKKKKBKKKkOOqOq',
    'OqO.OqKKKKKKKKkOOqqk',
    'qOqOOqKKKKKKKKkOOkKk',
    'qqkOkqKKKKKKKKkk.Oqk',
    'kKkOOkKKKKKKKKkO.Oqk',
    'OqkO.OqKKKKKKkO..Oqk',
    'OqkO.OkKKKKKKkO..Oqk',
    'OqkOOOOqKKKKkOOO.Oqk',
    'OqkOqqqKKKKKKqqkOOqk',
    'OqKqKKKKKKkKKKKKqqKk',
    'OqKKKKKKKkKKKKKKkKKk',
    'OqKKKKkkkKkkkkKkOqKk',
    'OqKkKKKKKkKKKKKkOkKk',
    'OkkOqKkkkKkkkkKkOOkk',
    '.OOOkKKKKkKKKKKkO.OO',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OqkkkKkkkkkO....',
    '....OqKKKkKKKKkO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPPPPPPppO....',
    '....OPPPpOOPPPpO....',
    '....OPPPpOOPpPpO....',
    '....OPPPpOOpOpO.....',
    '....OPpPpO.OkkO.....',
    '....OpOpO..OkkO.....',
    '.....OkkO.ODDDDO....',
    '.....OkkO.ODDDDO....',
    '....ODDDDO.OOOO.....',
    '....ODDDDO..........',
  ];

}
